<?php
/*************************************************************************************      
Name			:  PipelineMetricsBLL.php 
Author			:  A, Mohammed Khadar Khan
Created Date	:  7th-July-2012 
Description     :  Pipeline metrics page bll layer
Modified Date   :
Reason          :               
*************************************************************************************/
include("DAL/PipelineMetricsDAL.php");

function grand_total_graph_data_BLL($sector_name,$top25){
// TCV, WTCV data from stage 3-7 for the grand total graph based on month
$result37 = sum_tcv_wtcv_37_bymonth_DAL($sector_name,$top25);   
$graph_row_count37 =  mysql_num_rows($result37) or die("display_db_query1:" . mysql_error());
$column_count = mysql_num_fields($result37) or die("display_db_query2:" . mysql_error());

$i=0;
while($row = mysql_fetch_array($result37))
{
    while($row[0] != ($i+1))
    {
        $graphArray37_wtcv[$i]= 0; /*enter 0, if there is no data for tcv and wtcv*/
        $graphArray37_tcv[$i]= 0;
        $i++;
    }
    $graphArray37_wtcv[$i]= $row[1];
    $graphArray37_tcv[$i]= $row[2];
    $i++;
}

// TCV, WTCV data from stage 4-7 for the grand total graph based on month
$result47 = sum_tcv_wtcv_47_bymonth_DAL($sector_name,$top25);
$graph_row_count47 =  mysql_num_rows($result47) or die("display_db_query3:" . mysql_error());
$column_count = mysql_num_fields($result47) or die("display_db_query4:" . mysql_error());

$i=0;
while($row = mysql_fetch_array($result47))
{
    while($row[0] != ($i+1))
    {
        $graphArray47_wtcv[$i]= 0;
        $graphArray47_tcv[$i]= 0;
        $i++;
     }
     $graphArray47_wtcv[$i]= $row[1];
     $graphArray47_tcv[$i]= $row[2];
     $i++;
 }    

//sum of 'Sold' by month
$total_bookings = sum_sold_bymonth_DAL($sector_name,$top25);
echo mysql_num_rows($total_bookings);
if(mysql_num_rows($total_bookings) ==  0)       //if there is no data generated by the query assign 0's to sold values
{
    $total_bookings_row_count = 12;
    $column_no=0;
    for($i=0; $i<12 ; $i++)
    {
        $graph_total_bookings[$column_no]= 0;
    }
    
}
else
{
    $total_bookings_row_count =  mysql_num_rows($total_bookings) or die("display_db_query5_:" . mysql_error());
    $column_count = mysql_num_fields($total_bookings) or die("display_db_query6:" . mysql_error());

    $column_no=0;
    while($row = mysql_fetch_array($total_bookings))
    {
        $graph_total_bookings[$column_no]= $row[0];
        $column_no++;
    } 
}

// forming arrays to display cumulative graphs for sold, tcv, wtcv
//for Sold
$cumulative_sum = 0;
for($i=0; $i<$total_bookings_row_count ; $i++)
{
   $cumulative_sum = $cumulative_sum + $graph_total_bookings[$i];
   $bookings[$i]=$cumulative_sum/1000;
}

for(; $i< 12 ; $i++)                                    //maintaining the same cumulative value of bookings after the current month
$bookings[$i] = $bookings[$i-1]; 

//for tcv and wtcv
/*for($i=0; $i < $total_bookings_row_count ; $i++)       //TCV and WTCV take the same cumulative values as 'sold' upto the current month                                      
{
    $array_37_wtcv[$i]= $bookings[$i] ; 
    $array_37_tcv[$i]= $bookings[$i]  ;
}*/

$cumulative_sum_wtcv = 0;$cumulative_sum_tcv = 0;
for($i=0; $i<12 ; $i++)      //TCV and WTCV values after the current month are dependent on the pipeline data available from stage 3-7 + 'sold' data
{
    $cumulative_sum_tcv = $cumulative_sum_tcv + $graphArray37_tcv[$i];
    $display_tcv = ($cumulative_sum_tcv/1000) + $bookings[$i];
    $array_37_tcv[$i] = $display_tcv;
                            
    $cumulative_sum_wtcv = $cumulative_sum_wtcv + $graphArray37_wtcv[$i];
    $display_wtcv = ($cumulative_sum_wtcv/1000) + $bookings[$i];
    $array_37_wtcv[$i] = $display_wtcv;       
}

/*for($i=0; $i < $total_bookings_row_count ; $i++)        //TCV and WTCV take the same cumulative values as 'sold' upto the current month                                      
{
    $array_47_wtcv[$i] = $bookings[$i] ;
    $array_47_tcv[$i] = $bookings[$i]  ;
}*/

$cumulative_sum_wtcv = 0; $cumulative_sum_tcv = 0;
for($i=0; $i<12 ; $i++)              //TCV and WTCV values after the current month are dependent on the pipeline data available from stage 4-7 + 'sold' data
{
    $cumulative_sum_tcv = $cumulative_sum_tcv + $graphArray47_tcv[$i];
    $display_tcv = ($cumulative_sum_tcv/1000) + $bookings[$i];
    $array_47_tcv[$i] = $display_tcv;      
    
    $cumulative_sum_wtcv = $cumulative_sum_wtcv + $graphArray47_wtcv[$i];
    $display_wtcv = ($cumulative_sum_wtcv/1000) + $bookings[$i];
    $array_47_wtcv[$i] = $display_wtcv;                         
}
return array ($bookings,$array_37_tcv,$array_37_wtcv,$array_47_tcv,$array_47_wtcv,$total_bookings_row_count);
}

function sum_tcv_wtcv_37_company_BLL($sector_name,$top25)
{
    $company37 = sum_tcv_wtcv_37_company_DAL($sector_name,$top25);
    return $company37;
}

function sum_tcv_wtcv_47_company_BLL($sector_name,$top25)
{
    $company47 = sum_tcv_wtcv_47_company_DAL($sector_name,$top25);
    return $company47;
}

function sum_sold_company_BLL($sector_name,$top25)
{
    $sold = sum_sold_company_DAL($sector_name,$top25);
    return $sold;
}

function pipeline_metrics_table_data_BLL($sector_name,$top25)
{
    $pipeline_table_data = pipeline_metrics_table_data_DAL($sector_name,$top25);
    return $pipeline_table_data;
}
?>
